# Generated by Django 3.2.8 on 2022-03-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TacheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache', models.CharField(max_length=400, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
